services:
  sApache:
    image: httpd:latest
    volumes:
      - ./starship-sorades-13k:/usr/local/apache2/htdocs:ro
    expose:
      - "80"
  
  sDc:
    image: nginx:latest
    container_name: cNginx
    depends_on:
      - sApache
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8080"
  